[package]
name = "luau"
version = "0.1.0"
edition = "2021"

[lib]
name = "luau"
crate-type = ["dylib"]

[dependencies]

[build-dependencies]
bindgen = "0.71.1"
cc = "1.2.22"
cmake = "0.1.54"
csbindgen = "1.9.3"
