name: Build Luau - macOS

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }} on macOS
    runs-on: macos-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
          - target: aarch64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install Ninja and Make
        run: |
          brew install ninja || true

      - name: Build luau-ffi
        working-directory: native/luau-ffi
        env:
          CARGO_BUILD_TARGET: ${{ matrix.target }}
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luau-ffi-${{ matrix.target }}
          path: |
            native/luau-ffi/target/${{ matrix.target }}/release/libluau.*
