name: Build Luau

on:
  workflow_dispatch:

jobs:
  build-windows:
    uses: ./.github/workflows/build-luau.windows.yml
  build-linux:
    uses: ./.github/workflows/build-luau.linux.yml
  build-macos:
    uses: ./.github/workflows/build-luau.macos.yml
  build-ios:
    uses: ./.github/workflows/build-luau.ios.yml
  build-android:
    uses: ./.github/workflows/build-luau.android.yml