name: Build Luau - Android

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }} on Android
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - target: aarch64-linux-android
          - target: x86_64-linux-android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Set up toolchains
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib
          rustup target add ${{ matrix.target }}
          sudo apt-get install -y libc6-dev-i386

      - name: Install libc++
        run: |
          sudo apt-get update
          sudo apt-get install -y libc++-dev libc++abi-dev
          sudo apt-get install -y build-essential

      - name: Set up Android SDK & NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Set up Environment Variables for NDK
        run: |
          echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}"
          echo "PATH=${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV
          echo "PATH=${{ steps.setup-ndk.outputs.ndk-path}}/toolchains/x86_64-4.9/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV
        shell: bash

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Install Ninja and Make
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build make

      - name: Build luau-ffi
        working-directory: native/luau-ffi
        env:
          CARGO_BUILD_TARGET: ${{ matrix.target }}
          CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang
          CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android26-clang
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luau-ffi-${{ matrix.target }}
          path: |
            native/luau-ffi/target/${{ matrix.target }}/release/libluau.*
